{% set name = "noaa-coops" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/noaa_coops-{{ version }}.tar.gz
  sha256: 9b7853cd4b2961332e930723dee05b45a8539976cbd5a2550fd3577e3c20841f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9,<4.0
    - requests >=2.32.3,<3.0.0
    - numpy >=1.24.1,<2.0.0
    - pandas >=2.2.2,<3.0.0
    - zeep >=4.2.1,<5.0.0

test:
  imports:
    - noaa_coops
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/GClunies/noaa_coops
  summary: Python wrapper for NOAA Tides & Currents Data and Metadata
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
