{% set name = "noaa-coops" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/noaa_coops-{{ version }}.tar.gz
  sha256: 545ee6627699d909e4d035fae14f5cd8f43598ccd6324e88840d6aa181003fde

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - requests >=2.32.3
    - numpy >=1.24.1,<2.0.0
    - pandas >=2.2.2
    - zeep >=4.2.1

test:
  imports:
    - noaa_coops
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/GClunies/noaa_coops
  summary: Python wrapper for NOAA Tides & Currents Data and Metadata
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
